name: deployment
on:
  workflow_dispatch: 

env:
  CH_HOST: ${{ secrets.CH_HOST }}
  CH_DB_USER: ${{ secrets.CH_DB_USER }}
  CH_DB_SCHEMA: ${{ secrets.CH_DB_SCHEMA }}
  CH_DB_PASSWORD: ${{ secrets.CH_DB_PASSWORD }}
  GH_REF: ${{ github.ref }} 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      # git checkout 
      - name: checkout code
        uses: actions/checkout@v3
      
      # set up python version 
      - name: set up python 
        uses: actions/setup-python@v4
        with: 
          python-version: 3.10.8

      # # install python dependencies 
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r transforms/dbt/requirements.txt
      
      # install dbt packages
      - name: dbt deps
        run: |
          cd transforms/dbt/traffic_service_clickhouse
          dbt deps

      # checkout to main 
      - name: checkout to main
        uses: actions/checkout@v3
        with:
          ref: main
      
      # deploy dbt project
      - name: deploy dbt project 
        run: | 
          cd transforms/dbt/traffic_service_clickhouse
          dbt deps
          dbt run