name: deployment-prod
on:
  workflow_dispatch: 

env:
  GH_REF: ${{ github.ref }} 
  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws_region: ${{ secrets.AWS_REGION }}  

jobs:
  build: 
    runs-on: ubuntu-latest    
    steps: 
      # git checkout 
      - name: checkout code
        uses: actions/checkout@v3
      
      # set up docker buildx
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      # read env file from s3
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://traffic-monitor-env-s3-bucket/.env
          # destination:
          aws_access_key_id: ${{ env.aws_access_key_id }}
          aws_secret_access_key: ${{ env.aws_secret_access_key }}
          aws_region: ${{ env.aws_region }}

      - name: write to $github_env
        shell: bash
        run: cat .env | while read line || [[ -n $line ]]; do echo $line >> $GITHUB_ENV; done
          
      # login to prod aws ecr
      - name: login to aws ecr
        uses: docker/login-action@v2        
        with:
          registry: ${{ env.aws_dev_ecr}}
          username: ${{ env.aws_access_key_id }}
          password: ${{ env.aws_secret_access_key }}

      # bulid and push the docker image
      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          context: ./data-transformation/dbt
          push: true 
          tags: |
            $ {{ env.aws_dev_ecr }}:${{ github.sha }}

      # # set up python version 
      # - name: set up python 
      #   uses: actions/setup-python@v4
      #   with: 
      #     python-version: '3.10'

      # # # install python dependencies 
      # - name: install dependencies 
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r transforms/dbt/requirements.txt
      
      # # install dbt packages
      # - name: dbt deps
      #   run: |
      #     cd transforms/dbt/traffic_service_clickhouse
      #     dbt deps

      # # checkout to main 
      # - name: checkout to main
      #   uses: actions/checkout@v3
      #   with:
      #     ref: main
      
      # # deploy dbt project
      # - name: deploy dbt project 
      #   run: | 
      #     cd transforms/dbt/traffic_service_clickhouse
      #     dbt deps
      #     dbt run